### PR TITLE
Update to v2.0.1

### PR DESCRIPTION
**Pull request by szechyjs**

### CODE REVIEW

**Comment by szechyjs** [comment]
bump?

**Comment by dennisbaskin** [comment]
I apologize for not looking at this yet, I have not had the time, but I will look at the merge request within the next couple of days

**Comment by dennisbaskin** [comment]
Also I just saw that there was a version 3.0.0 https://github.com/mouse0270/bootstrap-notify/blob/master/bootstrap-notify.js considering updating to that instead, unless there is a desire to keep old versions for some reason.

**Comment by szechyjs** [comment]
3.0.0 seems fine with me. The main functionality in 2.0.1 that I needed was the x and y offset. This seems to be in 3.0 as well.

**Comment by dennisbaskin** [comment]
This has been updated to version 3.0 in another pull request and updated on RubyGems :smile: sorry for the long wait (this is being used by our company and I have to coordinate the release without breaking anything).

**Pull request closed without merging**
